# serverless.yml
# By: Juan Diego Cubillos
service: users
frameworkVersion: '3'
provider:
  name: aws
  runtime: python3.8
  region: us-east-2
  iamRoleStatements:
    - Effect: Allow
      Action:
        - DynamoDB:*
      Resource: 
        - arn:aws:dynamodb:us-east-2:969794511691:table/Users

#Serverless Functions
functions:
  create:
    handler: create.handler
    events:
      - http:
          path: user
          method: post

  read:
    handler: read.handler
    events:
      - http:
          path: user/{userid}
          method: get

  update:
    handler: update.handler
    events:
      - http:
          path: user/{userid}
          method: put

  delete:
    handler: delete.handler
    events:
      - http:
          path: user/{userid}
          method: delete

  listar:
    handler: list.handler
    events:
      - http:
          path: users
          method: get

# serverless resources
resources:
  Resources:
    UsersTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: Users
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: userid
            AttributeType: N
        KeySchema:
          - AttributeName: userid
            KeyType: HASH